/**
 * AI Detection Service
 * Detects AI-generated media using FREE heuristic analysis only
 * 
 * NO PAID EXTERNAL APIS - Uses only free methods:
 * - Source keyword analysis
 * - Metadata analysis (EXIF, file properties)
 * - File characteristics (size, dimensions, aspect ratios)
 * - Pattern detection
 * 
 * Future enhancements (all free):
 * - Local ML models (TensorFlow.js, ONNX.js)
 * - Open-source detection libraries
 * - Community-maintained models
 */

interface AIDetectionResult {
  isAiGenerated: boolean;
  confidence: number; // 0-100
  method: string;
  indicators: string[];
  metadata: {
    hasExif: boolean;
    hasWatermark: boolean;
    compressionArtifacts: boolean;
    pixelPatterns: string;
  };
}

/**
 * Analyze image metadata for AI generation indicators
 */
function analyzeImageMetadata(metadata: any): {
  hasExif: boolean;
  hasWatermark: boolean;
  compressionArtifacts: boolean;
  pixelPatterns: string;
} {
  return {
    hasExif: metadata.exif !== undefined && Object.keys(metadata.exif || {}).length > 0,
    hasWatermark: metadata.watermark !== undefined,
    compressionArtifacts: metadata.compression !== undefined,
    pixelPatterns: metadata.pixelPattern || 'unknown'
  };
}

/**
 * Detect AI-generated images using heuristics
 * 
 * Indicators of AI generation:
 * 1. Missing EXIF data (AI tools often strip metadata)
 * 2. Unusual pixel patterns (AI can create repetitive patterns)
 * 3. Perfect symmetry (AI often creates too-perfect images)
 * 4. Unusual file size vs dimensions ratio
 * 5. Source metadata (if source indicates AI tool)
 */
export async function detectAIGenerated(
  hash: string,
  metadata: any,
  source: string,
  imageMetadata?: {
    width?: number;
    height?: number;
    format?: string;
    size?: number;
  }
): Promise<AIDetectionResult> {
  const indicators: string[] = [];
  let confidence = 0;
  let isAiGenerated = false;

  // Check source for AI indicators
  const aiSourceKeywords = [
    'midjourney', 'dall-e', 'dalle', 'stable diffusion', 'stable-diffusion',
    'ai generated', 'ai-generated', 'ai art', 'aiart', 'generated by ai',
    'chatgpt', 'gpt', 'openai', 'runway', 'leonardo', 'lexica', 'nightcafe',
    'craiyon', 'imagen', 'firefly', 'adobe firefly', 'bing image creator'
  ];

  const sourceLower = source.toLowerCase();
  const hasAiSource = aiSourceKeywords.some(keyword => sourceLower.includes(keyword));

  if (hasAiSource) {
    indicators.push('Source indicates AI generation tool');
    confidence += 40;
  }

  // Analyze image metadata
  const metaAnalysis = analyzeImageMetadata(metadata);
  
  // Missing EXIF data is a strong indicator (but not definitive)
  if (!metaAnalysis.hasExif && imageMetadata) {
    indicators.push('Missing EXIF metadata (common in AI-generated images)');
    confidence += 15;
  }

  // Check file size vs dimensions ratio (AI images can have unusual ratios)
  if (imageMetadata && imageMetadata.width && imageMetadata.height && imageMetadata.size) {
    const pixels = imageMetadata.width * imageMetadata.height;
    const bytesPerPixel = imageMetadata.size / pixels;
    
    // Very low or very high bytes per pixel can indicate AI generation
    if (bytesPerPixel < 0.1 || bytesPerPixel > 10) {
      indicators.push('Unusual file size to dimensions ratio');
      confidence += 10;
    }
  }

    // Check for common AI image characteristics
  // Perfect aspect ratios (1:1, 16:9) are common in AI tools
  if (imageMetadata && imageMetadata.width && imageMetadata.height) {
    const width = imageMetadata.width;
    const height = imageMetadata.height;
    const aspectRatio = width / height;
    const perfectRatios = [1, 1.5, 1.777, 0.75, 0.667]; // 1:1, 3:2, 16:9, 3:4, 2:3
    
    if (perfectRatios.some(ratio => Math.abs(aspectRatio - ratio) < 0.01)) {
      indicators.push('Perfect aspect ratio (common in AI-generated images)');
      confidence += 5;
    }
    
    // Check for very high resolution (AI tools often generate in standard high-res)
    const totalPixels = width * height;
    if (totalPixels >= 4194304 && totalPixels <= 16777216) { // 2MP to 16MP range
      // Common AI generation resolutions
      const commonAiResolutions = [
        { w: 1024, h: 1024 }, // 1:1
        { w: 2048, h: 2048 }, // 1:1
        { w: 1920, h: 1080 }, // 16:9
        { w: 1024, h: 768 },  // 4:3
      ];
      
      const matchesCommon = commonAiResolutions.some(res => 
        Math.abs(width - res.w) < 10 && 
        Math.abs(height - res.h) < 10
      );
      
      if (matchesCommon) {
        indicators.push('Common AI generation resolution');
        confidence += 8;
      }
    }
  }

  // Check metadata for AI tool indicators
  const metadataStr = JSON.stringify(metadata).toLowerCase();
  if (metadataStr.includes('ai') || metadataStr.includes('generated')) {
    indicators.push('Metadata contains AI-related keywords');
    confidence += 20;
  }

  // Determine if AI-generated based on confidence threshold
  isAiGenerated = confidence >= 50;

  return {
    isAiGenerated,
    confidence: Math.min(100, confidence),
    method: 'heuristic-analysis',
    indicators,
    metadata: metaAnalysis
  };
}

/**
 * Enhanced AI detection using free/open-source methods only
 * Uses only heuristic analysis - no external paid APIs
 * 
 * Future free enhancements could include:
 * - Local ML models (TensorFlow.js, ONNX.js)
 * - Open-source AI detection libraries
 * - Community-maintained detection models
 */
export async function detectAIGeneratedAdvanced(
  imageUrl: string,
  imageBuffer?: Buffer
): Promise<AIDetectionResult | null> {
  // Currently using only free heuristic methods
  // No external paid APIs are used
  // This function is kept for future free enhancements (local ML models, etc.)
  
  return null;
}

/**
 * Combine multiple detection methods for higher accuracy
 * Uses only free heuristic methods - no paid external APIs
 */
export async function detectAIGeneratedCombined(
  hash: string,
  metadata: any,
  source: string,
  imageMetadata?: {
    width?: number;
    height?: number;
    format?: string;
    size?: number;
  },
  imageUrl?: string
): Promise<AIDetectionResult> {
  // Use heuristic detection (free, no external APIs)
  const heuristicResult = await detectAIGenerated(hash, metadata, source, imageMetadata);
  
  // Future: Could add free local ML models here (TensorFlow.js, etc.)
  // For now, we only use heuristic analysis
  
  return heuristicResult;
}

